name: Desktop Build Action
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  Build-Desktop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x desktop/gradlew
    - name: Build with Gradle
      run: cd desktop/ && ./gradlew jar
    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: mobapp-game-desktop
        path: ${{ github.workspace }}/desktop/build/libs/*.jar

