name: Build Action
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  Build-J2ME:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Test
        run: cd ${{ github.workspace }} && ls .
      - name: Build
        run: sudo dpkg --add-architecture i386 && sudo apt-get install libc6 && cd ${{ github.workspace }} && sudo dpkg -i ./bin/j2me_compiler/multiarch*.deb && ./bin/build.sh
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: mobapp-game-j2me
          path: ${{ github.workspace }}/bin/MobileApplication3.jar

