name: Build Action
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  Build-J2ME:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Test
        run: cd ${{ github.workspace }} && ls .
      - name: Build
        run: cd ${{ github.workspace }} && ./bin/build.sh
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: mobapp-game
          path: ${{ github.workspace }}/bin/MobileApplication3.jar

